---
title: "Importação Bases e limpeza de variáveis"
format: html
editor: visual
---

# Importação de dados 

## Importação e preparação dos dados (Passar a importação de dados e colocar logo no início)

```{r}
#| warning: false
#| message: false
#| error: false

set.seed(123)

rm(list = ls(all.names = TRUE)) 
required_packages <- c(
                       "tidyverse",
                       "rio",
                       "scales",
                       "here",
                       "patchwork",
                       "sf", 
                       "ggthemes",
                       "giscoR",
                       "eurostat",
                       "sysfonts", 
                       "showtext", 
                       "scales",
                       "geodata", 
                       "osmdata", 
                       "leaflet",
                       "janitor",
                       "assertr",
                       "data.validator",
                       "forcats",
                       "data.table",
                       "broom",
                       "gt",
                       "gtsummary",
                       "glm2",
                       "performance",
                       "see",
                       "readxl",
                       "purrr",
                       "tibble",
                       "ggridges",
                       "tidymodels",
                       "tidyclust",
                       "factoextra"
                       )      

for (pkg in required_packages) {
 
  if (!pkg %in% rownames(installed.packages())) {
    install.packages(pkg)
  }

  library(pkg, character.only = TRUE)
}
remove(required_packages)
remove(pkg)

```

```{r importation and cleaning}
gdh_base_raw <-  import("data/data_gdh/base_gdh_icd10_no_freg.csv")

code_residence <- import("data/data_gdh/codigos_residencia.csv") 
# Não foi necessário usar 

geo_linkage <- import("data/data_gdh/geo_linkage_2024_v6.csv")

comm_pt <- st_read("data/map_json_portugal/concelhos_portugal_light.json")


# residentes_2013 <- read_delim("data/populacao_residente_2013.csv", 
#     delim = ";", 
#     escape_double = FALSE, 
#     trim_ws = TRUE)

icd10_codes <- import("data/data_gdh/codigos_diagnostico_icd10.csv")

gdh_group <- import("data/data_gdh/grupos_gdh.csv")


```

# Limpeza de variáveis 

### Sexo 

-   sexo: 3ª categoria - "Indeterminado" contabilizar como NA

-   remove "Indeterminado"

```{r}

sexo_clean <-  gdh_base_clean |> 
  filter( sexo == "Indeterminado")
```

### Idade 

-   remove (-1) -

-   Total (-1) - 11

-   Considerar 0 ? - ver gdh

```{r}

idade_clean <- gdh_base_clean |> 
  mutate(
    idade_f = as.factor(idade)
  ) |>
  filter(
    idade == -1
  )
```

### Concelho e distrito 

-   código 99 - remover (= NA)

-   portanto quando distrito == "99" concelho também é

-   8% base de dados -

```{r}

gdh_dist <- gdh_base_clean |> 
  filter(
    cod_conc_chr == "99" | 
    cod_dist == "99" |
    dt_mun == "9999"
  )


```
